package:
  name: seqmagick
  version: "0.8.3"

source:
  url: https://files.pythonhosted.org/packages/77/6d/b40f210d0504545e0cfbf39d53bfff86381496d09173a47f8c77259f6b34/seqmagick-0.8.3.tar.gz
  sha256: 170eb5bd611bb9cfb50a965c1c757dafa7b4d0bba6b99ce5fb6eafa7c3fac47a

build:
  noarch: python
  entry_points:
    - seqmagick = seqmagick.scripts.cli:main
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python >3
    - pip
    - nose
    - biopython >=1.70
  run:
    - python >3
    - biopython >=1.70

test:
  imports:
    - seqmagick
    - seqmagick.scripts
    - seqmagick.subcommands
    - seqmagick.test
    - seqmagick.test.integration
    - seqmagick.test.integration.data

  commands:
    - seqmagick --help

about:
  home: http://github.com/fhcrc/seqmagick
  license: GNU General Public License (GPL)
  license_family: GPL
  summary: 'Tools for converting and modifying sequence files from the command-line'
