{% set name = "pyrodigal" %}
{% set version = "0.3.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/b3/93/142b6e4446e4df6e76919ad954fa6854fe1a3542f540692632eb5870d1d7/pyrodigal-0.3.2.tar.gz
  sha256: 7f004df8a8484ad7e5609a5d7125152ead69003df733ad7e5d320ce2840c16ba

build:
  number: 0
  skip: True  #[py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/althonos/pyrodigal
  license: GPL-3
  license_family: GPL
  license_file: COPYING
  summary: Python bindings to Prodigal, an ORF finder for microbial sequences.

extra:
  recipe-maintainers:
    - althonos
