{% set name = "nanocompore" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: ee45a72bf1339c5d4bce5008bf1aca08fb039f087f8275ea11628619400c338a

build:
  noarch: python
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - nanocompore = nanocompore.__main__:main

requirements:
  host:
    - pip
    - python >=3.6.1,<3.7.0a0
    - poetry >=0.12
  run:
    - matplotlib-base
    - numpy >=1.16.0
    - pandas
    - pyfaidx
    - python >=3.6.1,<3.7.0a0
    - pyyaml
    - scikit-learn =0.21
    - scipy >=1.2.0
    - seaborn
    - statsmodels >=0.9.0
    - tqdm
    - bedparse
    - importlib_metadata

test:
  commands:
    - nanocompore sampcomp --help
    - nanocompore simreads --help
    - nanocompore plot --help

about:
  home: "https://github.com/tleonardi/nanocompore"
  license: "GNU General Public v3 (GPLv3)"
  license_family: GPL3
  license_file: LICENSE
  summary: "Nanocompore identifies raw signal changes between two conditions dRNA-Seq data."

extra:
  recipe-maintainers:
    - bgruening
  identifiers:
    - usegalaxy-eu:nanocompore_db
