{% set version = '0.6.16' %}
{% set github = "https://github.com/hbc/bcbioBase" %}

package:
  name: r-bcbiobase
  version: "{{ version }}"

source:
  url: "{{ github }}/archive/v{{ version }}.tar.gz"
  sha256: 9df7b6264cf1d9cee9f61248c8601507b6ee51395c7c2a426867a1eb7a83950b

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
      # Depends:
    - r-base
      # Imports:
    - bioconductor-s4vectors >=0.24
    - r-basejump >=0.12.0
    - r-cli >=2.0
    - r-goalie >=0.4.1
    - r-plyr >=1.8
    - r-stringr >=1.4
      # Suggests:
    - r-rdrop2 >=0.8
  run:
      # Depends:
    - r-base
      # Imports:
    - bioconductor-s4vectors >=0.24
    - r-basejump >=0.12.0
    - r-cli >=2.0
    - r-goalie >=0.4.1
    - r-plyr >=1.8
    - r-stringr >=1.4
      # Suggests:
    - r-rdrop2 >=0.8

test:
  commands:
    - $R -e "library('bcbioBase')"

about:
  home: http://bioinformatics.sph.harvard.edu/bcbioBase/
  dev_url: "{{ github }}"
  license: MIT
  license_file: LICENSE
  summary: Base functions and generics for bcbio R packages.

extra:
  recipe-maintainers:
    - mjsteinbaugh
